name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [ {os : 'windows', arch: 'amd64'}, {os: 'linux', arch: 'arm64' }, {os: 'linux', arch: 'amd64' }]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Confirm Version
      run: go version

    - name: Build
      run: |
        GOOS=${{ matrix.targets.os }} GOARCH=${{ matrix.targets.arch }} make
        zip Premiumizemed_${{ env.RELEASE_VERSION }}-${{ matrix.targets.os }}-${{ matrix.targets.arch }}.zip build/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Premiumizemed_${{ env.RELEASE_VERSION }}-${{ matrix.targets.os }}-${{ matrix.targets.arch }}
        path: Premiumizemed_${{ env.RELEASE_VERSION }}-${{ matrix.targets.os }}-${{ matrix.targets.arch }}.zip
